services:
  postgres:
    image: postgres:15.12
    container_name: pr_service_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${db_name}
      POSTGRES_USER: ${db_user_name}
      POSTGRES_PASSWORD: ${db_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${db_port}:5432"

  app:
    build: .
    container_name: pull-request-app
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8000:8000"

volumes:
  postgres_data:
